name: Build and deploy image

env:
  DOCKER_HUB_REPO: ikrushkov/first-container-image

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - run: echo "Test application in workflow!"
  build:
    name: Build container and commit in dockerhub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [test]
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t $DOCKER_HUB_REPO:$(date '+%Y-%m-%d')-${GITHUB_SHA:0:8} .

      - name: Push to repository
        run: |
          docker login --username ikrushkov --password ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker image push --all-tags $DOCKER_HUB_REPO
